apiVersion: v1
kind: Namespace
metadata:
  name: pg-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-config
  namespace: pg-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: pg-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: pg-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: pg-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: pg-namespace

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: pg-namespace

